Fix exception on POSIX systems (#11)
In `bk7231tools.serial.BK7231Serial.__init__()`, after initializing
the `serial.Serial` object, calling its `set_buffer_size()` method
results in the following exception.

```
AttributeError: 'Serial' object has no attribute 'set_buffer_size'
File "[...]/bk7231tools/serial/__init__.py", line 28, in __init__
```

That method is peculiar to the [Windows implementation][1], and
doesn't exist in the POSIX (or java) implementations.

[1]: https://github.com/pyserial/pyserial/blob/master/serial/serialwin32.py#L418